### PR TITLE
2.0.0-DEV-SNAPSHOT PRE-RELEASE VER 1

### PR DESCRIPTION
**Pull request by JordanGS**
1. Fixed unclean shutdown due to large session files
2. Overall code clean up, formatting and variable changes
3. Overall UI cleanup and fixes
4. Added context functionality for Name, Include, Exclude and separated it
   from the target URL
5. Added various Attack options for Spider, AJAX Spider and Active Scan
6. Added authScriptParam by @mabdelmoez for testing only (requires his approval)
7. Removed some unnecessary code
8. Updated/redone all help files
9. Deprecated the AsUser methods in favor of more unified functionality
10. Added functionality to accept environment variables as well as build
    injector environment variables during regular build and pre-build
    (combined my own code and code by @whren). Fields which now accept
    environment variables include: ( **zapHost, zapPort, zapSettingsDir, contextName, includedURL, excludedURL, targetURL, reportName, sessionFilename, cmdLinesZap** )
11. Added a check to ensure that build fails if host or port are left empty
    in the job
12. Added WARNING label to JIRA functionality since it requires and add-on
    that is not bundled with ZAP, nor is it available via the marketplace.
13. Load Session and Persist Session are now mutually exclusive, you cannot pick both during a build config
14. Data Validation added to Load Session, Persist Session, Include in Context and ZAP Home, removed clazz for these from config.jelly since it conflicts when there is a java end validation
15. Changed workflow, if a Session is NOT Loaded and a Session is NOT Persisted then the build with fail without attempting anything else.

### CODE REVIEW

**Comment by JordanGS** [comment]
@mabdelmoez Review and let me know if it's good for commit.

@whren incorporated our two methods to give the best of both worlds.

**Comment by JordanGS** [comment]
@mabdelmoez updated the pull request, added 12, 13 and 14. Let me know if you have any issues with any of those.

**Comment by mabdelmoez** [comment]
@JordanGS All good ! Lets merge that one.
P.S: I no longer see the review button, I don't know why.

**Comment by JordanGS** [comment]
@mabdelmoez Not sure, but as long as you had a chance to take a look and you're happy with it :) Feedback is appreciated ofc.

**Pull request merged**
