### PR TITLE
Manage Alerts Filters

### PR DESCRIPTION
**Pull request by tlenaic**
I am developing a feature, that i think may be useful for enterprise and user.
My idea is, from an xml filter file where we notice the alert, the url, the new level... like on owasp zap proxy.
We could ignore alerts that are false positive when we generate report, and have a hand on which alerts we actually ignore or not.

Write now i have :
- add the section on Jelly.
- The file should be in the directory filter of our job jenkins
- I can parse my xml file.

the last thing is to call clientapi.alertfilter.addfilter(...)
which seem not existe in the last release of zap-clientapi. but we can find it in zap proxy and as a beta version here
 https://github.com/zaproxy/zap-api-java/tree/master/subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi

I would like to know what you think about that feature ?
and if you plan to release a new version of clientapi.java whith alertfilter.java ?
i join a timeline on how i see project using zap and jenkins.
alertfile

### CODE REVIEW

**Comment by thc202** [comment]
This plugin is no longer maintained, the new/maintained plugin is at https://github.com/jenkinsci/zap-plugin/

There's interest in a feature like that, please see/comment on https://issues.jenkins-ci.org/browse/JENKINS-39985

Regarding the Java ZAP API client, we'll release a new version soon (in any case it's still possible to call the APIs directly).

**Comment by tlenaic** [comment]
Thanks for the answer.

**Comment by tlenaic** [comment]
i don't now, if my question have been seen on the other link.
i want to know, if  in the methode addAlertFilter of the class AlertFilter, the string ruleId corresponds to the value of pluginId in my ZAP xml report ?

AND  for now, i am in my algorithm
 - i parse the xml file
 - add filters to the context
 - finally i run the active scan

do i, have miss a step ? because there is no changes in the report. 
i dont know if the method active scan check for filter in my context.
( I WORK with a session in jenkins without alerts, i erase all of them and i make sure the session was saved without )

**Comment by thc202** [comment]
Yes, better to use the other pull request. This one can be closed.

**Comment by tlenaic** [comment]
ok i  have write one pull request here :  https://github.com/jenkinsci/zap-plugin/pull/2

**Comment by thc202** [comment]
Right, I noticed that one :) I'll add some comments soon.

**Comment by JordanGS** [comment]
Not distributed anymore but allow the existing users of the plugin to use the latest version. Please migrate to: https://wiki.jenkins-ci.org/display/JENKINS/zap+plugin

**Comment by thc202** [comment]
Thanks for tidying up this :)

**Pull request closed without merging**
