### PR TITLE
Feature: Importing URLs for scanning

### PR DESCRIPTION
**Pull request by tlopesPT**
Implemented an option to import URLs to be scanned in job configuration.
Added a text area to config.jelly for the "import URLs" option.
Created the help file for the "import URLs" option.
Created config.properties to correctly display the name of the field.

### CODE REVIEW

**Comment by JordanGS** [comment]
@tlopesPT Hello, I have taken over the project. "Including URLs in Context" will be addressed in Pull Request #41, please let me know if you have any questions.

It however does not check for malformed URL's since it accept's regular expressions.

At this time i will close this pull request but if you have any questions or would like to reopen it or update, go ahead.

**Comment by thc202** [comment]
@JordanGS the proposed changes were not to include the URLs in context (although they need to) but to allow to provide URLs to be scanned (also useful for seeding the spiders).

**Comment by tlopesPT** [comment]
@thc202 That is correct.

@JordanGS There's a try-catch block for malformed URLs.

**Comment by JordanGS** [comment]
@tlopesPT My mistake, once version 2.0.0 is released if you can update your pull request, i would appreciate it. Or feel free to add it to the development branch which is the current version we are planning to release :)

**Comment by JordanGS** [comment]
@tlopesPT This version will stop being distributed, existing users can still use the latest version.

Please migrate to: https://github.com/JordanGS/zap-plugin and feel free to re-open a pull request of issue under the new plugin. (Expect a release of Monday, November 21st, 2016.

Cheers. 👍

**Pull request closed without merging**
