### PR TITLE
Development branch merge with my dev-features: authScriptParams, contextName and formatting

### PR DESCRIPTION
**Pull request by mabdelmoez**
Hi Jordan, As we discussed. Regards

### CODE REVIEW

**Comment by mabdelmoez** [comment]
I removed my feature "Scan Coverage Control" since you have been working on it, and we agreed on the new look & feel. Let me know if you want me to integrate it as well. 

That leaves us @ "authScriptParams" for fixing scriptBasedAuth and better flexibility and "contextName" feature. The rest was handled already. Others will follow after we merge this.

**Comment by JordanGS** [comment]
@mabdelmoez what did you do for context name? It was already there and had options to allow both pre build environment variables and environment injector variables?

**Comment by mabdelmoez** [comment]
I noticed that it was hardcoded as "context1". So gave the user the option to change. 
You can refer to https://github.com/jenkinsci/zaproxy-plugin/issues/32

Was it already configurable you mean ?

**Comment by JordanGS** [comment]
@mabdelmoez It was already configurable in the version i gave you, at least i thought it was?

Let's discuss on slack.

**Comment by mabdelmoez** [comment]
Some addressed issues in this pull were included in pull 41. This pull will be closed, a new pull will be requested addressing the remaining issues.

**Comment by mabdelmoez** [comment]
In https://github.com/jenkinsci/zaproxy-plugin/pull/44

**Pull request closed without merging**
